# Generated by Django 6.0.3 on 2026-04-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/covers/'),
        ),
        migrations.AddField(
            model_name='eventmedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/gallery/'),
        ),
    ]
