# Generated by Django 6.0.3 on 2026-04-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_campaign_objective_campaign_organizer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='organizer_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
