# Generated by Django 6.0.3 on 2026-04-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_campaign_organizer_assigned_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'verbose_name': 'Ndiguel', 'verbose_name_plural': 'Ndiguels'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Actualité', 'verbose_name_plural': 'Actualités'},
        ),
        migrations.AddField(
            model_name='campaign',
            name='illustrative_photo',
            field=models.ImageField(blank=True, null=True, upload_to='campaigns/photos/'),
        ),
    ]
