# Generated by Django 6.0.3 on 2026-04-26 13:31

from django.db import migrations


def migrate_campaign_event_to_fete(apps, schema_editor):
    Campaign = apps.get_model('events', 'Campaign')
    Event = apps.get_model('events', 'Event')
    Fete = apps.get_model('events', 'Fete')

    campaigns = Campaign.objects.filter(fete__isnull=True, event__isnull=False)
    for campaign in campaigns.iterator():
        event = Event.objects.filter(pk=campaign.event_id).first()
        if not event:
            continue
        fete, _created = Fete.objects.get_or_create(
            name=event.name,
            defaults={
                'description': event.description or '',
                'date': event.event_date,
                'recurrence': event.recurrence or 'none',
                'is_active': True,
                'created_by_id': event.created_by_id,
            },
        )
        campaign.fete_id = fete.id
        campaign.save(update_fields=['fete'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('events', '0007_fete_campaign_fete'),
    ]

    operations = [
        migrations.RunPython(migrate_campaign_event_to_fete, noop_reverse),
        migrations.RemoveField(
            model_name='campaign',
            name='event',
        ),
    ]
