# Generated by Django 6.0.3 on 2026-04-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_campaign_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmedia',
            name='event',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventMedia',
        ),
    ]
