# Generated by Django 6.0.3 on 2026-09-01 16:34

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_eventmedia_event_delete_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='illustrative_photo',
            field=models.ImageField(blank=True, null=True, upload_to='campaigns/photos/', validators=[core.validators.ValidateUploadSize()]),
        ),
    ]
