# Generated by Django 6.0.3 on 2026-10-07 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_campaign_illustrative_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fete',
            options={'ordering': ['name'], 'verbose_name': 'Événement', 'verbose_name_plural': 'Événements'},
        ),
    ]
