# Generated by Django 6.0.3 on 2026-09-01 16:34

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newspost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsgalleryimage',
            name='image',
            field=models.ImageField(upload_to='news/gallery/%Y/%m/', validators=[core.validators.ValidateUploadSize()]),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='news/covers/', validators=[core.validators.ValidateUploadSize()]),
        ),
    ]
