# Generated by Django 6.0.3 on 2026-04-20 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'Jëf', 'verbose_name_plural': 'Jëfs'},
        ),
    ]
