# Generated by Django 6.0.3 on 2026-04-22 03:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_pilotagesettings'),
        ('contributions', '0003_alter_donation_options'),
        ('events', '0006_alter_campaign_options_alter_event_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='bictorys_ref',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='checkout_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='external_ref',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['external_ref'], name='contributio_externa_d8dd64_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['bictorys_ref'], name='contributio_bictory_c7d651_idx'),
        ),
    ]
