# Generated by Django 6.0.3 on 2026-04-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0004_donation_bictorys_ref_donation_checkout_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('orange_money', 'Orange Money'), ('wave', 'Wave'), ('paypal', 'PayPal'), ('manual', 'Manual'), ('collector', 'Collector'), ('visa', 'Visa'), ('mastercard', 'Mastercard')], default='manual', max_length=20),
        ),
    ]
