# Generated by Django 6.0.3 on 2026-04-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0005_alter_donation_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('orange_money', 'Orange Money'), ('wave', 'Wave'), ('paypal', 'PayPal'), ('collector', 'Collector'), ('visa', 'Visa'), ('mastercard', 'Mastercard')], default='collector', max_length=20),
        ),
    ]
