# Generated by Django 6.0.3 on 2026-04-26 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_titlerequest_userdocument_alter_user_options_and_more'),
        ('contributions', '0006_alter_donation_payment_method'),
        ('events', '0007_fete_campaign_fete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='target_daara',
            field=models.ForeignKey(blank=True, help_text='Daara du membre bénéficiaire', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_donations', to='accounts.daara'),
        ),
        migrations.AddField(
            model_name='donation',
            name='wire_reference',
            field=models.CharField(blank=True, help_text='Référence de virement saisie par le membre', max_length=100),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('orange_money', 'Orange Money'), ('wave', 'Wave'), ('bictorys', 'Bictorys (carte)'), ('virement', 'Virement bancaire'), ('manual', 'Espèces (collecteur)'), ('paypal', 'PayPal'), ('collector', 'Collector'), ('visa', 'Visa'), ('mastercard', 'Mastercard')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_wire', 'Virement en attente'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='DonationArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='archive_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='contributions.donationarchive'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['archive_id'], name='contributio_archive_40ba3b_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['payment_status'], name='contributio_payment_8a90c7_idx'),
        ),
    ]
