# Generated by Django 6.0.3 on 2026-04-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0007_donation_target_daara_donation_wire_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
