# Generated by Django 6.0.3 on 2026-04-17 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_ldd_user_address_user_birth_date_user_blood_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daara',
            name='ldd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daaras', to='accounts.ldd'),
        ),
    ]
