# Generated by Django 6.0.3 on 2026-04-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_daara_ldd'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_salons', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Paramètre de Pilotage',
                'verbose_name_plural': 'Paramètres de Pilotage',
            },
        ),
    ]
