# Generated by Django 6.0.3 on 2026-04-26 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_legacy_titles(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    MemberTitle = apps.get_model('accounts', 'MemberTitle')

    for user in User.objects.exclude(legacy_title__isnull=True).exclude(legacy_title=''):
        title_name = (user.legacy_title or '').strip()
        if not title_name:
            continue
        title, _ = MemberTitle.objects.get_or_create(name=title_name)
        user.title_id = title.id
        user.save(update_fields=['title'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_pilotagesettings'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('refused', 'Refusé')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('national_id', "Carte Nationale d'Identité"), ('passport', 'Passeport'), ('voter_id', "Carte d'Électeur"), ('driver_license', 'Permis de Conduire')], max_length=20)),
                ('image', models.ImageField(upload_to='documents/%Y/%m/')),
                ('image_verso', models.ImageField(blank=True, null=True, upload_to='documents/%Y/%m/')),
                ('doc_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validé'), ('rejected', 'À corriger')], default='pending', max_length=10)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='driver_license_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='national_id_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='user',
            name='voter_id',
        ),
        migrations.AddField(
            model_name='user',
            name='title_change_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='title_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text="Obligatoire si pas d'email", max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='MemberTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_titles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='user',
            old_name='title',
            new_name='legacy_title',
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.membertitle'),
        ),
        migrations.RunPython(migrate_legacy_titles, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='user',
            name='legacy_title',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('email__isnull', False), ('phone__isnull', False), _connector='OR'), name='user_email_or_phone_required'),
        ),
        migrations.AddField(
            model_name='titlerequest',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='titlerequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_title_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='titlerequest',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.membertitle'),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userdocument',
            unique_together={('user', 'doc_type')},
        ),
    ]
