# Generated by Django 6.0.3 on 2026-09-01 16:34

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_titlerequest_userdocument_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[core.validators.ValidateUploadSize()]),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='image',
            field=models.ImageField(upload_to='documents/%Y/%m/', validators=[core.validators.ValidateUploadSize()]),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='image_verso',
            field=models.ImageField(blank=True, null=True, upload_to='documents/%Y/%m/', validators=[core.validators.ValidateUploadSize()]),
        ),
    ]
