# Generated by Django 6.0.3 on 2026-09-18 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_normalisation_telephones_e164'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ldd',
            options={'ordering': ['code', 'name']},
        ),
        migrations.AlterField(
            model_name='daara',
            name='ldd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daaras', to='accounts.ldd'),
        ),
        migrations.AlterField(
            model_name='ldd',
            name='code',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='ldd',
            unique_together={('code', 'name')},
        ),
    ]
