# Generated by Django 6.0.3 on 2026-09-18 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_ldd_code_non_unique_et_daara_protege'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daara',
            options={'ordering': ['name']},
        ),
    ]
