# Generated by Django 6.0.3 on 2026-10-07 20:56
"""
Retours de la réunion client d'octobre 2026.

1. Genre : le choix « Autre » disparaît, il ne reste que Homme / Femme.
   Les comptes qui portaient `gender='other'` passent à NULL — « non
   renseigné » — AVANT que le champ ne perde ce choix : laisser la valeur
   en base la rendrait invalide au premier enregistrement du profil.
   Le retour arrière ne restaure rien : on ne sait plus qui avait « Autre ».

2. Rôle : le libellé de `chef_daara` devient « Coordinateur du Daara ».
   La valeur stockée ne change pas — seuls les `choices` bougent.
"""

from django.db import migrations, models


def genre_autre_vers_non_renseigne(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(gender='other').update(gender=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_tri_alphabetique_des_daaras'),
    ]

    operations = [
        migrations.RunPython(genre_autre_vers_non_renseigne, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Homme'), ('female', 'Femme')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('chef_daara', 'Coordinateur du Daara'), ('collector', 'Collector'), ('member', 'Member'), ('tutelle', 'Tutelle')], default='member', max_length=20),
        ),
    ]
