# Generated by Django 6.0.3 on 2026-04-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0002_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_role',
            field=models.CharField(choices=[('all', 'All Roles'), ('admin', 'Admin Only'), ('chef_daara', 'Chef Daara Only'), ('collector', 'Collector Only'), ('member', 'Member Only')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='announcement',
            name='urgency',
            field=models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20),
        ),
    ]
