# Generated by Django 6.0.3 on 2026-09-01 16:34

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0006_fcmtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/', validators=[core.validators.ValidateUploadSize()]),
        ),
    ]
