# Generated by Django 6.0.3 on 2026-09-12 04:30

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0007_alter_message_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/', validators=[core.validators.ValidateUploadSize(), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp', 'heic', 'heif', 'pdf', 'doc', 'docx', 'odt', 'rtf', 'txt', 'xls', 'xlsx', 'ods', 'csv', 'ppt', 'pptx', 'odp', 'mp3', 'm4a', 'aac', 'ogg', 'opus', 'wav', 'amr', 'mp4', 'mov', '3gp', 'webm', 'zip'], message="Ce type de fichier n'est pas accepté en pièce jointe. Formats autorisés : images, PDF, documents bureautiques, audio, vidéo et archives ZIP.")]),
        ),
    ]
