# Generated by Django 6.0.3 on 2026-10-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0008_alter_message_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='target_role',
            field=models.CharField(choices=[('all', 'All Roles'), ('admin', 'Admin Only'), ('chef_daara', 'Coordinateurs du Daara uniquement'), ('collector', 'Collector Only'), ('member', 'Member Only')], default='all', max_length=20),
        ),
    ]
